Models/Account.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TVA_Assessment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int code { get; set; }
        public int person_code { get; set; }
        public string account_number { get; set; }
        public decimal outstanding_balance { get; set; }
        public Nullable<bool> closed { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}

Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TVA_Assessment.Utilities;
using TVA_Assessment.Models;

namespace TVA_Assessment.Controllers
{
    public class AccountsController : Controller
    {
        // GET: Accounts
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAccounts(int userId)
        {
            using (var db = new TVAEntities())
            {
                var accounts = db.Accounts.Where(x => x.person_code == userId).Select(x => new
                {
                    Id = x.code,
                    x.account_number,
                    x.outstanding_balance,
                    x.closed,
                    canClose = (x.outstanding_balance == 0 ? true : false)
                });

                string searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

                if (!string.IsNullOrEmpty(searchValue))
                {
                    accounts = accounts.Where(m => m.account_number.Contains(searchValue) || m.outstanding_balance.ToString().Contains(searchValue));
                }
                return Json(FormDataTables.LoadDataTable(accounts, Request), JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetAccount(int accountId)
        {
            using (var db = new TVAEntities())
            {
                var account = db.Accounts.Where(x => x.code == accountId).FirstOrDefault();
                return View(account);
            }
        }

        public ActionResult NewAccount(int userId)
        {
            var newAccount = new Account()
            {
                person_code = userId
            };
            return View(newAccount);
        }

        public JsonResult ToggleAccount(int accountId)
        {
            try
            {
                using (var db = new TVAEntities())
                {
                    var account = db.Accounts.Where(x => x.code == accountId).FirstOrDefault();
                    if (account.outstanding_balance == 0)
                    {
                        account.closed = (account.closed != null && account.closed == true ? false : true);
                        db.Entry(account).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new { Success = false, Message=$"Please settle the balance of {account.outstanding_balance} first." }, JsonRequestBehavior.AllowGet);

                }
            }
            catch (Exception E)
            {
                return Json(new { Success = false, E.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult CRUD(Account account)
        {
            try
            {
                using (var db = new TVAEntities())
                {
                    if (account.code > 0)
                    {
                        var dbAccount = db.Accounts.Find(account.code);
                        if (account.account_number != dbAccount.account_number && AccNoExists(account.account_number))
                        {
                            return Json(new { Success = false, Message = "" }, JsonRequestBehavior.AllowGet);
                        }
                        //db.Entry(dbAccount).CurrentValues.SetValues(account);
                        dbAccount.account_number = account.account_number;
                        dbAccount.person_code = account.person_code;
                        db.Entry(dbAccount).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    else
                    {
                        //New
                        if (AccNoExists(account.account_number))
                        {
                            return Json(new { Success = false, Message = $"Account number {account.account_number} is already taken!" }, JsonRequestBehavior.AllowGet);
                        }
                        account.closed = false;
                        db.Accounts.Add(account);
                        db.SaveChanges();
                    }
                    return Json(new { Success = true, accountId = account.code }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception E)
            {
                return Json(new { Success = false, E.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public bool AccNoExists(string accNum)
        {
            using (var db = new TVAEntities())
            {
                var account = db.Accounts.Where(x => x.account_number == accNum).FirstOrDefault();
                if (account != null)
                {
                    return true;
                }
            }
            return false;
        }
    }
}

Controllers/PersonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic;
using System.Web;
using System.Web.Mvc;
using TVA_Assessment.Models;
using TVA_Assessment.Utilities;

namespace TVA_Assessment.Controllers
{
    public class PersonsController : Controller
    {
        // GET: Persons       
        public PersonsController()
        {
        }
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        public JsonResult GetPersons()
        {
            using (var db = new TVAEntities())
            {
                var persons = db.Persons.Select(x => new
                {
                    Id = x.code,
                    x.name,
                    x.surname,
                    x.id_number
                });

                string searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

                if (!string.IsNullOrEmpty(searchValue))
                {
                    persons = persons.Where(m => m.name.Contains(searchValue) || m.surname.Contains(searchValue) || m.id_number.Contains(searchValue));
                }
                return Json(FormDataTables.LoadDataTable(persons, Request));
            }
        }
        [HttpGet]
        public ActionResult CRUD(int Id)
        {
            using (var db = new TVAEntities())
            {
                var person = db.Persons.Where(x => x.code == Id).FirstOrDefault();
                return View(person);
            }

        }
        [HttpPost]
        public JsonResult CRUD(Person person)
        {
            try
            {
                using (var db = new TVAEntities())
                {
                    //Update
                    if (person.code > 0)
                    {
                        var dbRecord = db.Persons.Where(x => x.code == person.code).FirstOrDefault();
                        if (dbRecord != null)
                        {
                            //compare ID numbers
                            if (dbRecord.id_number != person.id_number && UserExists(person.id_number))
                            {
                                return Json(new { Success = false, Message = $"ID Number {person.id_number} is already in use." }, JsonRequestBehavior.AllowGet);
                            }
                            dbRecord.id_number = person.id_number;
                            dbRecord.name = person.name;
                            dbRecord.surname = person.surname;
                            //db.Entry(dbRecord).CurrentValues.SetValues(person);
                            db.Entry(dbRecord).State = System.Data.Entity.EntityState.Modified;
                            db.SaveChanges();
                        }
                    }
                    //New person
                    else
                    {

                        if (UserExists(person.id_number))
                        {
                            return Json(new { Success = false, Message = $"ID Number {person.id_number} is already in use." }, JsonRequestBehavior.AllowGet);
                        }
                        db.Persons.Add(person);
                        db.SaveChanges();
                    }
                    return Json(new { Success = true,person_code= person.code }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception E)
            {
                return Json(new { Success = false, E.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult NewPerson()
        {
            return View();
        }

        public bool UserExists(string idNumber)
        {
            using (var db= new TVAEntities())
            {
                var persons = db.Persons.Where(x => x.id_number == idNumber).FirstOrDefault();
                if (persons != null)
                {
                    return true;
                }
            }
            return false;
        }
    }
}

Views/Accounts/GetAccount.cshtml
@model TVA_Assessment.Models.Account

@{
    ViewBag.Title = "GetAccount";
}

@using (Ajax.BeginForm("CRUD", "Persons", new AjaxOptions { OnSuccess = "onSuccess", OnFailure = "onFailure" }, new { }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @{
            if (Model.closed == false)
            {

            }
            else
            {
                <h4>Account || <span class="text-warning">CLOSED</span></h4>
            }
        }
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.code)
        @Html.HiddenFor(model => model.person_code)


        <div class="form-group">
            @Html.LabelFor(model => model.account_number, "Acc No.", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.account_number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.account_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.outstanding_balance, $"Outstanding balance", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" readonly value="@Model.outstanding_balance" />
            </div>
        </div>

        @if (Model.closed == false)
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        }
    </div>
}

<div class="col-md-12">
    <h4>Transactions</h4>
    @{
        if (Model.closed == false)
        {
            <a href="/Transactions/NewTransaction?accountId=@Model.code">Add a new transaction</a>
        }
    }
    <hr />
    <table id="dtTransactions" class="display" style="width:100%"></table>
</div>

<div>
    <a href="/Persons/CRUD?Id=@Model.person_code">Back to List</a>
</div>  
<script>
    $(document).ready(function () {
        getTransactions(@Model.code)
    });

    function onSuccess(data) {
        console.log(data);
    }

    function onFailure(data) {
        console.log(data);
    }
</script>

Views/Accounts/NewAccount.cshtml
@model TVA_Assessment.Models.Account

@{
    ViewBag.Title = "NewAccount";
}

@using (Ajax.BeginForm("CRUD", "Accounts", new AjaxOptions { HttpMethod ="POST", OnSuccess="onSuccess", OnFailure="onFailure" }, new { }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>New Account</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.person_code)

        <div class="form-group">
            @Html.LabelFor(model => model.account_number, "Acc No.", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.account_number, new { htmlAttributes = new { @class = "form-control", @required="required" } })
                @Html.ValidationMessageFor(model => model.account_number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


<div class="col-md-12" id="divTransactions" style="display:none">
    <h4>Transactions</h4>
    <a href="/Transactions/NewTransaction?accountId=@Model.code">Add a new transaction</a>
    <hr />
    <table id="dtTransactions" class="display" style="width:100%"></table>
</div>


<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>
    $(document).ready(function () {
        var result = loadTransactions(@Model.code);
        if (result == true)
        {
            $("#divTransactions").show();
            loadTransactions(@Model.code);
        }
    });

    function loadTransactions(accountId) {
        if (accountId > 0) {
            return true;
        }
        return false;
    }

    function onSuccess(data) {
        var success = data.Success;
        if (success == true) {
            //go to accounts edit page
            window.location.href = "/Accounts/GetAccount?accountId=" +data.accountId;
        }
        else {
            alert(data.Message);
        }
    }

    function onFailure(data) {
        alert(data.Message)
    }
</script>