Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TVA_Assessment.Utilities;
using TVA_Assessment.Models;

namespace TVA_Assessment.Controllers
{
    public class AccountsController : Controller
    {
        // GET: Accounts
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetAccounts(int userId)
        {
            using (var db = new TVAEntities())
            {
                var accounts = db.Accounts.Where(x => x.person_code == userId).Select(x => new
                {
                    Id = x.code,
                    x.account_number,
                    x.outstanding_balance,
                    x.closed,
                    canClose = (x.outstanding_balance == 0 ? true : false)
                });

                string searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

                if (!string.IsNullOrEmpty(searchValue))
                {
                    accounts = accounts.Where(m => m.account_number.Contains(searchValue) || m.outstanding_balance.ToString().Contains(searchValue));
                }
                return Json(FormDataTables.LoadDataTable(accounts, Request), JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetAccount(int accountId)
        {
            using (var db = new TVAEntities())
            {
                var account = db.Accounts.Where(x => x.code == accountId).FirstOrDefault();
                return View(account);
            }
        }

        public ActionResult NewAccount(int userId)
        {
            var newAccount = new Account()
            {
                person_code = userId
            };
            return View(newAccount);
        }

        public JsonResult ToggleAccount(int accountId)
        {
            try
            {
                using (var db = new TVAEntities())
                {
                    var account = db.Accounts.Where(x => x.code == accountId).FirstOrDefault();
                    if (account.outstanding_balance == 0)
                    {
                        account.closed = (account.closed != null && account.closed == true ? false : true);
                        db.Entry(account).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                        return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
                    }
                    return Json(new { Success = false, Message=$"Please settle the balance of {account.outstanding_balance} first." }, JsonRequestBehavior.AllowGet);

                }
            }
            catch (Exception E)
            {
                return Json(new { Success = false, E.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult CRUD(Account account)
        {
            try
            {
                using (var db = new TVAEntities())
                {
                    if (account.code > 0)
                    {
                        var dbAccount = db.Accounts.Find(account.code);
                        if (account.account_number != dbAccount.account_number && AccNoExists(account.account_number))
                        {
                            return Json(new { Success = false, Message = "" }, JsonRequestBehavior.AllowGet);
                        }
                        //db.Entry(dbAccount).CurrentValues.SetValues(account);
                        dbAccount.account_number = account.account_number;
                        dbAccount.person_code = account.person_code;
                        db.Entry(dbAccount).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    else
                    {
                        //New
                        if (AccNoExists(account.account_number))
                        {
                            return Json(new { Success = false, Message = $"Account number {account.account_number} is already taken!" }, JsonRequestBehavior.AllowGet);
                        }
                        account.closed = false;
                        db.Accounts.Add(account);
                        db.SaveChanges();
                    }
                    return Json(new { Success = true, accountId = account.code }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception E)
            {
                return Json(new { Success = false, E.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public bool AccNoExists(string accNum)
        {
            using (var db = new TVAEntities())
            {
                var account = db.Accounts.Where(x => x.account_number == accNum).FirstOrDefault();
                if (account != null)
                {
                    return true;
                }
            }
            return false;
        }
    }
}

Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TVA_Assessment.Models;
using TVA_Assessment.Utilities;

namespace TVA_Assessment.Controllers
{
    public class TransactionsController : Controller
    {
        public TVAEntities db { get; set; }
        // GET: Transactions
        public TransactionsController()
        {
            db = new TVAEntities();
        }

        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetTransactions(int accountCode)
        {
            using (var db = new TVAEntities())
            {
                var transactions = db.Transactions.Where(x => x.account_code == accountCode).Select(x => new
                {
                    Id = x.code,
                    transaction_date = x.transaction_date.ToString(),
                    x.capture_date,
                    x.amount,
                    x.description
                });
                string searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

                if (!string.IsNullOrEmpty(searchValue))
                {
                    transactions = transactions.Where(m => m.description.Contains(searchValue) || m.amount.ToString().Contains(searchValue) || m.transaction_date.ToString().Contains(searchValue)
                    || m.capture_date.ToString().Contains(searchValue));
                }
                return Json(FormDataTables.LoadDataTable(transactions, Request), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult GetTransaction(int transactionId)
        {
            using (var db = new TVAEntities())
            {
                var transaction = db.Transactions.Where(x => x.code == transactionId).FirstOrDefault();
                return View(transaction);
            }
        }

        public ActionResult NewTransaction(int accountId)
        {
            var newTransaction = new Transaction
            {
                account_code = accountId
            };
            return View(newTransaction);
        }

        [HttpPost]
        public JsonResult CRUD(Transaction transaction)
        {
            try
            {
                using (var db = new TVAEntities())
                {
                    if (transaction.code > 0)
                    {

                        decimal tempDb = 0;
                        transaction.capture_date = DateTime.Now;
                        var dbTransaction = db.Transactions.Where(x => x.code == transaction.code).FirstOrDefault();
                        //db.Entry(dbTransaction).CurrentValues.SetValues(transaction)
                        tempDb = dbTransaction.amount;
                        dbTransaction.amount = transaction.amount;
                        if (transaction.amount > tempDb)
                        {
                            transaction.amount =  transaction.amount - tempDb ;
                        }
                        else
                        {
                            transaction.amount = (tempDb - transaction.amount)*-1;
                            
                        }
                        dbTransaction.transaction_date = transaction.transaction_date;
                        dbTransaction.description = transaction.description;
                        db.Entry(dbTransaction).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    else
                    {
                        transaction.capture_date = DateTime.Now;
                        db.Transactions.Add(transaction);
                        db.SaveChanges();
                    }
                    //update the outstanding balance
                    var dbAccount = db.Accounts.Where(x => x.code == transaction.account_code).FirstOrDefault();
                    if (dbAccount != null)
                    {
                        dbAccount.outstanding_balance += transaction.amount;
                        db.Entry(dbAccount).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Json(new { Success = true }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception E)
            {
                return Json(new { Success = false, E.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

Views/Transactions/GetTransaction.cshtml
@model TVA_Assessment.Models.Transaction
@using TVA_Assessment.Models;
@{
    ViewBag.Title = "GetTransaction";
    var canEdit = false;
    using (var db = new TVAEntities())
    {
        var transactionAcc = db.Accounts.Where(x => x.code == Model.account_code).FirstOrDefault();
        canEdit = (transactionAcc != null && transactionAcc.closed == true ? false : true);
    }
}

@using (Ajax.BeginForm("CRUD", "Transactions", new AjaxOptions { HttpMethod = "POST", OnSuccess = "onSuccess", OnFailure = "onFailure" }, new { }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.code)
        @Html.HiddenFor(model => model.account_code)
        <div class="form-group">
            @Html.LabelFor(model => model.transaction_date, "Transaction date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<input type="text" class="form-control" id="js-date">*@
                @Html.EditorFor(model => model.transaction_date, new { htmlAttributes = new { @class = "form-control", @type = "text", @id = "js-date" } })
                @Html.ValidationMessageFor(model => model.transaction_date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount, "Amount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control", @type = "number", @id = "txtAmount", @required="required" , @onchange="onChange" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (canEdit)
        { 
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
        }
    </div>
}

<div>
   @* @Html.ActionLink("Back to List", "GetAccount", "Accounts", new { accountId = Model.account_code })*@
    <a href="/Accounts/GetAccount?accountId=@Model.account_code">Back to List</a>
</div>

<script>
    $(document).ready(function ()
    {
        $('#js-date').datepicker(
            { "endDate": new Date() });

        $('#datepicker').datepicker('update', '@Model.transaction_date');
        var parsed = parseFloat(@Model.amount);
        $('#txtAmount').val(parsed);
    });

     function onSuccess(data) {
        if (data.Success == true) {
            window.location.href = "/Accounts/GetAccount?accountId=" +@Model.account_code;
        }
        else {
            alert(data.Message);
        }
    }

    function onFailure(data) {
        alert(data.Message);
    }

    function onChange() {
        var amt = $('#txtAmount').val();
        if (amt == 0) {

        }
        else {

        }
    }
</script>

Views/Transactions/GetTransactions.cshtml
@model TVA_Assessment.Models.Transaction

@{
    ViewBag.Title = "GetTransactions";
}

<h2>GetTransactions</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.code)

        <div class="form-group">
            @Html.LabelFor(model => model.account_code, "account_code", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("account_code", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.account_code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.transaction_date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.transaction_date, new { htmlAttributes = new { @class = "form-control", @type="datetime" } })
                @Html.ValidationMessageFor(model => model.transaction_date, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Transactions/NewTransaction.cshtml
@model TVA_Assessment.Models.Transaction

@{
    ViewBag.Title = "NewTransaction";
}

@using (Ajax.BeginForm("CRUD", "Transactions", new AjaxOptions { HttpMethod = "POST", OnSuccess = "onSuccess", OnFailure = "onFailure" }, new { }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.account_code)
        <div class="form-group">
            @Html.LabelFor(model => model.transaction_date, "Transaction date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*<input type="text" class="form-control" id="js-date">*@
                @Html.EditorFor(model => model.transaction_date, new { htmlAttributes = new { @class = "form-control", @type = "text", @id = "js-date", @required="required" } })
                @Html.ValidationMessageFor(model => model.transaction_date, "", new { @class = "text-danger" })
            </div>



            @*<div class="input-append date" id="dp3" data-date="" data-date-format="dd-mm-yyyy">
                    <input class="span2" size="16" type="text" value="12-02-2012" id="dtSelectedDate" name="transaction_date">
                    <span class="add-on"><i class="icon-th"></i></span>
                </div>*@
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.amount,"Amount", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control", @type="number" } })
                @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description,"Description", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control",@required="required" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="/Accounts/GetAccount?accountId=@Model.account_code">Back to List</a>
</div>

<script>

    $(document).ready(function () {
        
        $('#js-date').datepicker({
            "endDate": new Date(),
             "autoclose":true
        });
        $('#js-date').datepicker('update',new Date());
    });

    function onSuccess(data) {
        if (data.Success == true) {
            window.location.href = "/Accounts/GetAccount?accountId=" +@Model.account_code;
        }
        else {
            alert(data.Message);
        }
    }

    function onFailure(data) {
        alert(data.Message);
    }
</script>